version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: underscore
    versions:
    - 1.12.0
    - 1.12.1
    - 1.13.0
  - dependency-name: meteor-node-stubs
    versions:
    - 1.0.1
    - 1.0.2
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: lodash
    versions:
    - 4.17.20
